### ISSUE TITLE
Add ability to ban user when ID is missing (or update docs)

### ISSUE THREAD

**Issue by ro31337** [metacircu1ar/bot#1]
Some users don't have at-nicknames (like `@Dok_zzz`), so you cannot add them to bot. For example:

<img width="683" alt="image" src="https://github.com/metacircu1ar/bot/assets/1477672/428eb877-1aa2-471d-9d11-71f81a6b5351">

There should be a way to ban them as well. Probably the numeric identifier would just work? (or not?) But how do you get one?

**Comment by metacircu1ar** [comment]
Ability to specify the user by id is implemented from the start and it's described here:
https://github.com/metacircu1ar/bot/blob/main/settings.rb#L14

You can specify the user by user name:
```ruby
{
  id: '@Dok_zzz'
}
```
Or you can use a user id, which prevents the bot from stopping to recognize the user, if they change their user name:
```ruby
{
  id: 'ID:156111338'
}
```
To figure out a user id, you can either find it in the logs(it gets printed every time a message is received, see https://github.com/metacircu1ar/bot/blob/main/bot.rb#L314), or you can just use a Telegram bot, such as 'RawDataBot'(just forward a message to it and it will give you back a user id). You can use the second way only if the user didn't hide their account. But if the account is hidden, you can always look up their id in the logs.

As an example, let's say you want to add a certain user(let's use the one from your screenshot) with the id of 5921037928:
```
  {
    id: 'ID:5921037928',
    rule_by_weekday: [0,0,0,0,0,nil,nil]
  }
```

**Comment by metacircu1ar** [comment]
Documentation was updated with more examples and instructions.
